name: "Kubectl Multi-line Command Action"
description: "Kubectl multiline command support for communicating with AWS EKS clusters"
branding:
  icon: 'anchor'  
  color: 'blue'
inputs:
  command:
    description: "List of kubectl commands"
    required: true
outputs:
  result:
    description: "Output of the kubectl commands"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.command }}
